//# Number of braces found 9
//# Number of braces found 0
//# power found 1 times using ^[ ]*(power)
//# primary found 1 times using ^[ ]*(primary)
//# factor found 1 times using ^[ ]*(factor)
//# term found 1 times using ^[ ]*(term)
//# arith found 1 times using ^[ ]*(arith)
//# comparison found 1 times using ^[ ]*(comparison)
//# not_test found 1 times using ^[ ]*(not_test)
//# and_test found 1 times using ^[ ]*(and_test)
//# or_test found 1 times using ^[ ]*(or_test)
    
    LEFTPAREN : "("
    RIGHTPAREN : ")"
    LEFTBRACE : "{"
    RIGHTBRACE : "}"
    LSQUAREB : "["
    RSQUAREB : "]"
    COMMA : ","
    COLON : ":"
    SEMI : ";"
    PERIOD : "."
    PWR : "**"
    MULT : "*"
    DIV : "/"
    CROSS : "^"
    PLUS : "+"
    MINUS : "-"
    ISEQUAL : "=="
    NEQ : "!="
    GTE : ">=" 
    LTE : "<="
    GT : ">"
    LT : "<"
    BADOR : "||"
    BADAND : "&&"
    
    EQUALS : "="
    APPEND : "++="
    AUGADD : "+="
    AUGMIN : "-="
    AUGMUL : "*="
    AUGDROP : "--=" 
    
    augop : APPEND | AUGADD | AUGMIN | AUGDROP | AUGMUL | EQUALS 

    
    INTEGER : /[0-9]+/
    OCTINT : /0o[0-7]+/
    HEXINT : /0x[0-9A-Fa-f]+/
    BININT : /0b[0-1]+/
    MISSING : "?"
    NULL : "NULL"
    
    real : ((INTEGER "." (INTEGER)*)|("." INTEGER))[("E"|"e"i) ["+"|"-"] INTEGER ]
    
    imaginary : (real | INTEGER) ("j"i|"J")
    LONGSTRING : /'''[^\\][.\n]*'''|"""[^\\][.\n]*"""/
    SHORTSTRING : /'[^']*'|"[^"]*"/
    AND : "and"i
    OR : "or"i
    IN : "in"i
    NOT : "not"i
    DO : "do"i
    FOR : "for"i
    LOOP : "loop"i
    AS : "as"i
    WITH : "with"i
    WHERE : "where"i
    ELSE : "else"i
    ELSEIF : /"else if"|"elseif"i/
    NEXT : "next"i
    BREAK : "break"i
    IF : "if"i
    FUNCTION : "function"i
    REPEAT : "repeat"i
    ID : /[A-Za-z_][A-Za-z0-9_$]*/
    COMMENT : /#.*/
    %ignore COMMENT
    WHITESPACE : /[ \t\r\n]+/
    %ignore WHITESPACE
    
    literal : SHORTSTRING | LONGSTRING | INTEGER | HEXINT | OCTINT | BININT | NULL | MISSING | real | imaginary 
    
    ident : ID 
    
    enclosure : parenth_form | list_display | table_display 
    parenth_form : LEFTPAREN expression_list RIGHTPAREN 
    
    list_display : LSQUAREB  expression_list RSQUAREB 
    expression_list : expression ( COMMA expression )* 
    
    table_display : LEFTBRACE  table_contents RIGHTBRACE 
    table_contents : table_entry ( COMMA table_entry )* 
    table_entry : SHORTSTRING  COLON  expression 
    att_primary : ident | attributeref | subscription | call 
?primary : att_primary | literal | enclosure 
    attributeref : att_primary "."  ( ID | INTEGER )  
    subscription : primary  "["  (proper_slice | slice_list | dotlist)  "]" 
    dotlist :  dotlist_element ("," dotlist_element )* 
    dotlist_element : ("."  ident  "="  expression)
    
    proper_slice : short_slice | long_slice 
    short_slice : COLON | (expression  COLON  expression) | (COLON expression) | (expression  COLON) 
    long_slice : short_slice  COLON  expression 
    slice_list : (expression | proper_slice) ( COMMA (expression | proper_slice) )* 
    
    call : ident  LEFTPAREN [expression_list] RIGHTPAREN 
?power : primary  [ PWR  factor ] 
    
?factor : power |  (PLUS|MINUS)  factor  
?term : factor | (term (MULT|DIV|CROSS) factor ) 
?arith : term | ( arith ( PLUS | MINUS ) term ) 
    restricted_comp_operator : GT | LT | GTE | LTE | NEQ | ISEQUAL 
    comp_operator : restricted_comp_operator | IN | (NOT IN) 
?comparison : arith | (comparison  comp_operator  arith ) 
?not_test : comparison | (NOT  not_test) 
?and_test : not_test  (  (AND | BADAND )  not_test )* 
?or_test  : and_test  ( (OR | BADOR )  and_test )* 
    expression : or_test 
    statements : statement | (statements statement) 
    statement : simple_statement | compound_statement 
    simple_statement : small_statement ( ";"  small_statement )* 
    small_statement : assignment | dotlist_assign | BREAK | NEXT 
    assignment :  lhs augop rhs 
    lhs : expression_list 
    rhs : expression_list 
    dotlist_assign : ident "("  dotlist  ")" 
    
    compound_statement : if_stmt | for_stmt | do_stmt | loop_stmt
                         | with_stmt | repeat_stmt | funcdef 
    suite : statement | "{" statements "}" 
    
    if_stmt : IF "(" expression ")" suite (else_if_stmt)* [else_stmt]
    else_stmt : ELSE  suite 
    else_if_stmt : ELSEIF  "("  expression  ")" suite 
    for_stmt : FOR  (id_list | "[" id_list "]")  IN  expression_list  suite 
    id_list : [id_list  ","]  ident 
    
    loop_stmt :  LOOP ident AS ident [":"  ident  [restricted_comp_operator  ident]] suite 
    do_stmt : DO ident  "=" expression  ","  expression  [","  expression] suite 
    repeat_stmt : REPEAT suite 
    with_stmt : WITH  ident  AS  ident  suite 
    funcdef : FUNCTION  ident  "("  arglist  ")"  suite 
    arglist : one_arg | (arglist COMMA one_arg) 
    one_arg : ident  ":"  "["  expression  ","  expression  "]" 
    input : statements 

